---
output: word_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

04-May-2021

Dear Mr. Fife,

Manuscript ID JIPM-2021-0034 entitled "First report of the *Brevipalpus*-transmitted (Trombidiformes: Tenuipalpidae) *Orchid fleck dichorhavirus* infecting three ornamentals in the United States" which you submitted to the Journal of Integrated Pest Management, has been reviewed and will be reconsidered for publication after the completion of the major revisions as noted. The comments of the reviewer(s) are included at the bottom of this letter.

Your revised manuscript should be uploaded within 45 days. Please let us know if you will require an extension. The due date is 18-Jun-2021.

To revise your manuscript, log into [hyperlink removed]  and enter your Author Centre, where you will find your manuscript title listed under "Manuscripts with Decisions."  Under "Actions," click on "Create a Revision."  Your manuscript number has been appended to denote a revision.

You may also click the below link to start the revision process.

*** PLEASE NOTE: This is a two-step process. After clicking on the link, you will be directed to a webpage to confirm. ***

[hyperlink removed]

Manuscript revision instructions
- Please ensure your paper follows journal style and requirements as listed in the instructions to authors: [hyperlink removed]
- Please highlight the changes to your manuscript within the document by using the track changes mode in MS Word or by using bold or colored text. Please also include a point-by-point response to reviews as well as a clean version (non-track changes version) of the paper.
- If your paper was created in LaTeX, please upload the PDF along with the tex files.
- Please delete any outdated files (e.g., the original manuscript, any outdated figures, etc.) before uploading the revised files.
- Figures should be submitted as separate files and not inserted into the main document. Figures should be submitted as at least 300 dpi (600 dpi for line graphs) and in one of the following file types: tif, eps, rtf, ppt/pptx, xls/xlsx, editable PDF, ps, psd, ai, gif, or png.

Once again, thank you for submitting your manuscript to the Journal of Integrated Pest Management and I look forward to receiving your revision.



Sincerely,
Dr. Nathan Walker
Subject Editor, Journal of Integrated Pest Management nathan.walker\@okstate.edu ESA Editorial Office: 3 Park Place, Suite 307, Annapolis, MD 21401-3722, USA. Editorial Office Phone: 1-301-731-4535.

\newpage

**Response to Decision Letter from the authors:**

**We thank you for dedicating your time to review our manuscript.**

**We believe that our revisions have addressed the errors and concerns mentioned. We are extremely grateful for your patience and thoughtful comments.**

**Thank you for your assistance,**

**-- The Authors**
 
\newpage

Reviewer(s)' Comments to Author:

#### Reviewer: 1

Comments to the Author
JIPM-2021-0034

This manuscript reports the discovery of orchid fleck virus infecting ornamental ground cover plants in Florida, USA.  The authors observed symptomatic plants of the family Asparagaceae in two northern counties of the state, and also identified brevipalpid mites on these plants, which may serve as the putative vector of the virus.  The discovery of OFV being potentially widespread in ornamental plants in Florida is an issue for those growing these (and other) plants in the family that are a host to these flat mites. There exists a threat to orchid and citrus industries, and I think it is worth discussing in the manuscript any speculation on why OFV has not been reported in orchids or citrus if the pathogen and vectors appear so widespread in the state.  Since the journal selected by the authors does focus on IPM, I think discussion of potential control measures to reduce the impact and spread of this virus is warranted.

A small note: the authors refer to cilevirus(es) in at least three locations in the manuscript.  There is no introduction or indication of why this virus is relevant to the study.  Unless this relevance is addressed, I would recommend removing such text.

For the mite descriptions, there seems to be inconsistency in providing taxonomic authorities.  My understanding is that the authorities should be used upon introduction, but not afterwards.  For example, see how Brevipalpus californicus is mentioned in L48, L64, L113, L164 etc.

The wording, organization, and grammar of the manuscript require significant revision for clarity and accuracy; perhaps more than I can offer below.  More notably, some references are either incorrect, or interpreted incorrectly.

In the abstract it is mentioned that additional leaf samples were collected in Leon and Alachua counties, and in the following sentence it states that partial genome sequence confirmed the presence of OFV.  Are these sentences linked? In the main text it appears only the samples from Leon County were actually found to be positive for OFV; the samples from Alachua were only examined for mites.  I think this is an important clarification; are the authors basing their claim of the virus being widespread in Florida (L51) based on symptoms, or actually detecting OFV in both counties. Infection by different dichorhaviruses can result in similar symptoms; diagnostics are critical.

L33: “Orchid fleck virus (OFV) is a dichorhavirus that infects over 50 plant species belonging to the families Asparagaceae, Orchidaceae, and Rutaceae.  The only known vectors for…”

L37: (Liriope and Ophiopogon spp.)

L40: “…Sanger sequencing.”

L41: remove “the known” and “the NCBI”

L42: I see no mention of a qPCR assay in the main text

L43: “…possibly infected plants of the family Asparagaceae from…”

L44: please elaborate on “Identification of partial genome sequence…” is this sequence from the PCR products or was HTS performed on the samples?

L48: perhaps identify what s.l. means; authorities are provided elsewhere in the manuscript

L49: italicize “Brevipalpus”

L59: Virus species should not be abbreviated; remove “(OFV)”

L60: virus families are italicized (Rhabdoviridae)

L63: replace “sole” with “only known”

L64: “group of mites” vs “sensu lato”?

L69: I don’t think referencing figures 1 and 2 are appropriate here

L73,76: is listing the second author the correct way to distinguish articles for this journal?  Rather than “a” or “b” after publication year?

L77: remove “: (Citrus)

L78: Olmedo-Velarde et al. is not an appropriate reference here

L82: “In June 2020,…”; (Lirope spp.)

L83: belongs

L85: perhaps “monocotyledonous liliod plants native to southeastern Asia (Chase…”

L86: is it appropriate to provide an authority for the genus (Ker Gawler)?

L92: none of these virus names should be italicized; INSV and TSWV are orthotospoviruses – why mentioned separately?

L97: “…as well as Aspidistra elaitor Blume (Asparagaceae), which was suspected…”

L103: “Lirope sp.”

L108: how many sites?

L127: This is incorrect: Blanchfield et al 2001 identified a virion larger than OFV, and the sample was negative for OFV when tested by RT-PCR.

L134: Nolinoideae

L145: The ICTV is not responsible for classification below species level, and as such, does not recognize virus strains; scientists and experts can recognize strains, but the  ICTV does not.

L152: “including Vanilla spp. in southern Florida…”

L154: a reference for this statement is advisable

L155: “…found that the virus which previously affected…”

L165: “…vectors of dichorhaviruses (Knorr 1968,…”

L168: “…identify the vector(s) of OFV in Florida…”

Table 1:
L338: “…with symptoms of orchid fleck virus infection found in…”
I am a little concerned about reporting on plants with symptoms, vs confirmed by diagnostics.  As mentioned earlier, different dichorhaviruses can cause similar symptoms in the same host.  Although remote, there is the possibility another virus could be responsible for the symptoms in a different location

Figure captions:
Please use “orchid fleck virus (OFV)” when describing a physical virus, and "Orchid fleck dichorhavirus" (in italics) when describing the species.

**Response to Reviewer 1:**
**Thank you for reviewing our article. We have made the following changes based on your remarks:**

<!-- - Added discussion on why OFV has not been reported in orchids or citrus if the pathogen and vectors appear so widespread in the state. -->

<!-- - Added discussion of potential control measures to reduce the impact and spread of this virus is warranted. -->

- We have removed all references to cileviruses
- We have corrected inconsistencies with taxonomic authorities
- 

The wording, organization, and grammar of the manuscript require significant revision for clarity and accuracy; perhaps more than I can offer below.  More notably, some references are either incorrect, or interpreted incorrectly.

In the abstract it is mentioned that additional leaf samples were collected in Leon and Alachua counties, and in the following sentence it states that partial genome sequence confirmed the presence of OFV.  Are these sentences linked? In the main text it appears only the samples from Leon County were actually found to be positive for OFV; the samples from Alachua were only examined for mites.  I think this is an important clarification; are the authors basing their claim of the virus being widespread in Florida (L51) based on symptoms, or actually detecting OFV in both counties. Infection by different dichorhaviruses can result in similar symptoms; diagnostics are critical.

L33: “Orchid fleck virus (OFV) is a dichorhavirus that infects over 50 plant species belonging to the families Asparagaceae, Orchidaceae, and Rutaceae.  The only known vectors for…”

L37: (Liriope and Ophiopogon spp.)

L40: “…Sanger sequencing.”

L41: remove “the known” and “the NCBI”

L42: I see no mention of a qPCR assay in the main text

L43: “…possibly infected plants of the family Asparagaceae from…”

L44: please elaborate on “Identification of partial genome sequence…” is this sequence from the PCR products or was HTS performed on the samples?

L48: perhaps identify what s.l. means; authorities are provided elsewhere in the manuscript

L49: italicize “Brevipalpus”

L59: Virus species should not be abbreviated; remove “(OFV)”

L60: virus families are italicized (Rhabdoviridae)

L63: replace “sole” with “only known”

L64: “group of mites” vs “sensu lato”?

L69: I don’t think referencing figures 1 and 2 are appropriate here

L73,76: is listing the second author the correct way to distinguish articles for this journal?  Rather than “a” or “b” after publication year?

L77: remove “: (Citrus)

L78: Olmedo-Velarde et al. is not an appropriate reference here

L82: “In June 2020,…”; (Lirope spp.)

L83: belongs

L85: perhaps “monocotyledonous liliod plants native to southeastern Asia (Chase…”

L86: is it appropriate to provide an authority for the genus (Ker Gawler)?

L92: none of these virus names should be italicized; INSV and TSWV are orthotospoviruses – why mentioned separately?

L97: “…as well as Aspidistra elaitor Blume (Asparagaceae), which was suspected…”

L103: “Lirope sp.”

L108: how many sites?

L127: This is incorrect: Blanchfield et al 2001 identified a virion larger than OFV, and the sample was negative for OFV when tested by RT-PCR.

L134: Nolinoideae

L145: The ICTV is not responsible for classification below species level, and as such, does not recognize virus strains; scientists and experts can recognize strains, but the  ICTV does not.

L152: “including Vanilla spp. in southern Florida…”

L154: a reference for this statement is advisable

L155: “…found that the virus which previously affected…”

L165: “…vectors of dichorhaviruses (Knorr 1968,…”

L168: “…identify the vector(s) of OFV in Florida…”

Table 1:
L338: “…with symptoms of orchid fleck virus infection found in…”
I am a little concerned about reporting on plants with symptoms, vs confirmed by diagnostics.  As mentioned earlier, different dichorhaviruses can cause similar symptoms in the same host.  Although remote, there is the possibility another virus could be responsible for the symptoms in a different location

Figure captions:
Please use “orchid fleck virus (OFV)” when describing a physical virus, and "Orchid fleck dichorhavirus" (in italics) when describing the species.


#### Reviewer: 2

Comments to the Author
The authors presented a well-written and illustrated communication about the co-occurrence of OFV and putative vector species (Brevipalpus spp.) in Florida, US.

My primary suggestion is that they be more specific about referring that the disease was reported in Florida. Other regions of the country were not part of the current work and should not be suggested as having a broad distribution.

I made a few editions, suggesting proper spellings for species “Family” names and the use of correct reference directly on the manuscript file attached.

Kitajima et. al. (2011) - correct reference mentioned is:
Kitajima E W, Chagas CM, Harakava R, Calegario RF, Freitas-Astúa J, Rodrigues JCV, Childers, CC. 2011. Citrus Leprosis in Florida, USA, appears to have been caused by the Nuclear Type of Citrus Leprosis Virus (CiLV-N). Virus Reviews & Research 16:1-5.


**Response to Reviewer 2:**
**Thank you for reviewing our article. We have made the following changes based on your remarks:**


**Response to PDF edits (Reviewer #?):**
**Thank you for reviewing our article. We have made the following changes based on your remarks:**

Accepted edits:

- L3 - 'the United States' $\rightarrow$ 'Florida'

- L33 - 'Orchid Fleck Virus' $\rightarrow$ '*Orchid fleck dichorhavirus*'

- L155 - reference manager error: citation link '\@Kitajima2011b' $\rightarrow$ citation link '\@Kitajima2011a' (produces correct reference)

- fixed reference manager errors: added brackets {} around capitalized words {} and italic species names '{\\textit{}}' to protect case. also: Asparagalean, Amaryllidaceae, Asparagaceae, Xanthorrhoeaceae, *Rhabdoviridae*, Asparagaceae, RNA, *Psilanthus*


Italicized all instances of *Rhabdoviridae*

- L321 - no need to italicize Asparagaceae, it is a plant family
